# Ingress resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName:
  rules:
  - host: "go-web.local"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: go-web
            port:
              number: 80
  
        
